[development]
address = "0.0.0.0"
port = 2019
workers = 1
log = "normal"
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 2019
workers = 4
log = "normal"
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 2019
workers = 8
log = "critical"
limits = { forms = 32768 }

